handle missing temp file

diff --git a/setup-environment-service b/setup-environment-service
--- a/setup-environment-service
+++ b/setup-environment-service
@@ -7,6 +7,19 @@ YELLOW='\033[1;33m'
 BLUE='\033[1;36m'
 NC='\033[0m' # No Color
 
+TEMP_SERVICE_FILE=temp.service
+
+if [[ ! -f ${TEMP_SERVICE_FILE} ]]; then
+    echo -e "----------------------------------------------------"
+    echo -e "${YELLOW}${TEMP_SERVICE_FILE}${LIGHT_RED} not found!$NC"
+    echo -e "----------------------------------------------------"
+    echo -e "The simplest solution is to get a fresh copy of"
+    echo -e "${YELLOW}${TEMP_SERVICE_FILE}${NC} and try again. Here is one way to"
+    echo -e "get a fresh copy:"
+    echo -e "${LIGHT_GREEN}wget https://raw.githubusercontent.com/charliecalvert/elven-systemd-tools/master/temp.service${NC}"
+    echo -e "----------------------------------------------------"
+    exit 1
+fi
 
 # You should define the following environment variables.
 # Then run: source setup-environment-service
@@ -23,8 +36,8 @@ echo -e "SYSTEMD_PROJECT_NAME is set to: $BLUE$SYSTEMD_PROJECT_NAME$NC"
 echo -e "SERVICE FILE is set to $BLUE$SERVICE_FILE$NC"
 echo -e "DESCRIPTION is set to $BLUE$SYSTEMD_DESCRIPTION$NC"
 echo -e "SYSTEMD_PORT is set to $BLUE$SYSTEMD_PORT$NC"
-echo -e "Renaming$YELLOW temp.service$NC to $YELLOW$SYSTEMD_PROJECT_NAME.service"$NC
+echo -e "Renaming$YELLOW ${TEMP_SERVICE_FILE}$NC to $YELLOW$SYSTEMD_PROJECT_NAME.service"$NC
 
-mv temp.service $SYSTEMD_PROJECT_NAME.service
+cp ${TEMP_SERVICE_FILE} $SYSTEMD_PROJECT_NAME.service
 
 echo -e "If the above looks good, run ./mod-service"
